### ISSUE TITLE
证书好像不能用, 已经无法登录了

### ISSUE THREAD

**Issue by saltedfisssh** [zfjdhj/mimikkoAutoSignV4#2]
报错如下
call_api error: code=StatusCode.UNAVAILABLE message=failed to connect to all addresses; last error: UNKNOWN: ipv4:47.117.161.78:443: Ssl handshake failed: SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

**Comment by zfjdhj** [comment]
大概是网站证书过期了，已修复
